[project]
authors = ["Pierre Marijon <pierre@marijon.fr>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "etc"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
snakemake = ">=8.27.1,<9"
jupyter = ">=1.1.1,<2"
altair = ">=5.5.0,<6"
pandas = ">=2.2.3,<3"
toolz = ">=1.0.0,<2"
