add_newline = false

format = """
$username$hostname$directory$package$git_branch$git_commit$git_state$git_status$rust$conda$battery$time
$character
"""

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"


